name: eclipse-skeleton
recipe: laravel
config:
  webroot: public
  php: '8.2'
  via: nginx
  database: mariadb:10.6
  xdebug: coverage
services:
  appserver:
    type: php:custom
    xdebug: "debug,develop"
    overrides:
      image: slimdeluxe/php:8.2-v1.0
      volumes:
        - "~/www/packages:/opt/php/packages"
  database:
    creds:
      database: eclipse
      user: developer
      password: developer
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
    database:
      type: mariadb:10.6
proxy:
  mailhog:
    - mail.eclipse-skeleton.lndo.site
  pma:
    - pma.eclipse-skeleton.lndo.site
tooling:
  test:
    service: appserver
    description: Run tests
    cmd: "composer test"
  npm:
    service: appserver
