name: eclipse-skeleton
recipe: laravel
config:
  webroot: public
  php: '8.0'
  via: nginx
  database: mariadb:10.6
  xdebug: coverage
services:
  database:
    creds:
      database: eclipse
      user: developer
      password: developer
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
    database:
      type: mariadb:10.6
proxy:
  mailhog:
    - mail.eclipse-skeleton.lndo.site
  pma:
    - pma.eclipse-skeleton.lndo.site
